### ISSUE TITLE
Syntax error at top-level `if` statements (e.g. `if erlang { ... }`).

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [gleam-lang/otp#25]
I can't compile, open a shell for, or test this code. (I'd like to tweak the tests to do my own experiments.) Whenever I try I get an error like this:

```
jeff@jbb-dell:otp-clone$ rebar3 shell
===> Verifying dependencies...

error: Syntax error
   ┌─ /home/jeff/code/concurrent-langs/gleam/by-others/otp-clone/_build/default/lib/gleam_stdlib/src/gleam/int.gleam:34:1
   │
34 │ if erlang {
   │ ^^ I was not expecting this.

Expected one of: An import, const, type, or function.

===> Unable to compile Gleam project
jeff@jbb-dell:otp-clone$
```

I grepped for it and there are a lot of "if erlang" and "if javascript" clauses, but almost all of them are in the project's `_build/` subfolder, which is not under version control -- that is, my own system appears to have built it. The `src/` and `test/` subfolders don't even mention the word `javascript`.

**Comment by lpil** [comment]
Hi @JeffreyBenjaminBrown , for that version of the stdlib you will need Gleam v0.17.0-rc1

**Comment by JeffreyBenjaminBrown** [comment]
Thanks for responding so fast, @lpil.

I upgraded to Gleam 16.1 and I'm still getting that error:
```
jeff@jbb-dell:otp-clone$ gleam --version
gleam 0.16.1

jeff@jbb-dell:otp-clone$ rebar3 --version
rebar 3.17.0 on Erlang/OTP 24 Erts 12.0.4

jeff@jbb-dell:otp-clone$ rebar3 shell
===> Verifying dependencies...

error: Syntax error
   ┌─ /home/jeff/code/concurrent-langs/gleam/by-others/otp-clone/_build/default/lib/gleam_stdlib/src/gleam/int.gleam:34:1
   │
34 │ if erlang {
   │ ^^ I was not expecting this.

Expected one of: An import, const, type, or function.

===> Unable to compile Gleam project
```

**Comment by lpil** [comment]
Apologies, I got my versions mixed up. v0.17.0-rc1 is required. If you wish to wait until v0.17.0 is released in the next week or so then the previous version of the stdlib can be used.

**Comment by JeffreyBenjaminBrown** [comment]
Thanks again! How? 

Editing `rebar.config` to specify version 0.16 instead of 0.17 doesn't seem to do it -- it still downloads stdlib 0.17:

```
jeff@jbb-dell:otp$ rm _build/ -rf
jeff@jbb-dell:otp$ git --no-pager diff
diff --git a/rebar.config b/rebar.config
index 81b4670..bc0db09 100644
--- a/rebar.config
+++ b/rebar.config
@@ -8,6 +8,6 @@
 {project_plugins, [rebar_gleam]}.

 {deps, [
-    {gleam_stdlib, "~> 0.17"},
+    {gleam_stdlib, "~ 0.16"},
     {gleam_erlang, "~> 0.1"}
 ]}.
jeff@jbb-dell:otp$ rebar3 shell
===> Fetching rebar_gleam v0.1.0
===> Analyzing applications...
===> Compiling rebar_gleam
===> Verifying dependencies...
===> Fetching gleam_erlang v0.1.0
===> Fetching gleam_stdlib v0.17.0

error: Syntax error
   ┌─ /home/jeff/code/concurrent-langs/gleam/by-others/otp/_build/default/lib/gleam_stdlib/src/gleam/int.gleam:34:1
   │
34 │ if erlang {
   │ ^^ I was not expecting this.

Expected one of: An import, const, type, or function.

===> Unable to compile Gleam project
jeff@jbb-dell:otp$
```

(I'd upgrade to v17rc1 but I'm on NixOS and I still don't understand how to add packages.)

**Comment by lpil** [comment]
If you've a rebar.lock file I believe it'll use those versions over what is in the config, so you may wish to unlock that dep or delete the lock file entirely.

Sorry about the awkward UX here, we will be replacing rebar with a tool of our own design in the near future.

**Comment by JeffreyBenjaminBrown** [comment]
No worries! I eventually got it working.

I've submitted a pull request that adds some introductory material to the README so that future users have an easier time.
