### ISSUE TITLE
Seemingly outdated documentation for `untyped_send`

### ISSUE THREAD

**Issue by cognivore** [gleam-lang/otp#27]
# Why?

The process.gleam module is seemingly the root of actor model in Gleam.
Documentation for `untyped_send` is the first non-trivial thing newcomers see, and currently it is unclear.

# What?

 - [ ] Clear up (remove "not not", long sentences), 
 - [ ] Address the [missing Channel type conundrum](https://discord.com/channels/768594524158427167/811254431051808778/892706161600638998),
 - [ ] If possible, [add moduledoc](https://discord.com/channels/768594524158427167/811254431051808778/892708582913605652).

# How?

 - [ ] Figure out what "Channel type" was (I suggest using git-temporal plugin for VSCode! It's awesome!)
 - [ ] Learn how it evolved into #(Sender(t), Receiver(t))
 - [ ] Describe this approach, preferrably in the moduledoc section of the module, where the notion of channels gets introduced (we think it's process.gleam)
 - [ ] Mention this approach briefly in place of outdated "see the Channel type" reference.

**Comment by lpil** [comment]
Thanks for the report, these docs are quite out of date and need improving. Let's do this for sure.
