### ISSUE TITLE
Bug: actor not unmonitoring finished task

### ISSUE THREAD

**Issue by arothuis** [gleam-lang/otp#39]
I have an actor that processes a task via `task.async` and `task.try_await`.
I always seem to get `Actor discarding unexpected message: DOWN` after the task has finished.

As I understand it, the actor that creates the task monitors it. 
The task is completed and goes 'down' and the actor reports this as a warning.

As suggested by @lpil on Discord, changes seem to be needed in these places, i.e. adding a call to `process.demonitor_process`:
https://github.com/gleam-lang/otp/blob/e4478fec30b36550a02caefb09f686cde2af5d33/src/gleam/otp/task.gleam#L89-L91
https://github.com/gleam-lang/otp/blob/e4478fec30b36550a02caefb09f686cde2af5d33/src/gleam/otp/task.gleam#L119-L123

To reproduce:
```gleam
pub fn main() {
  let loop = fn(msg, state) {
    task.async(fn() { state })
    |> task.try_await(500)

    Continue(state)
  }

  assert Ok(subject) = actor.start(0, loop)

  actor.send(subject, 1)
  process.sleep(1000)
}
```

Variants to test:
- `try_await`
- `try_await_forever`

**Comment by lpil** [comment]
Thank you
