### ISSUE TITLE
Naming of abstractions

### ISSUE THREAD

**Issue by lpil** [gleam-lang/otp#4]
What should we name our abstractions?

Here are the current names:

## Process

The lowest level abstraction. Generally this is not to be used by programmers, instead one of the other abstractions is to be used.

This matches Erlang's naming.

## Actor

A process that has a loop function that handles typed messages, can trap exits, and can monitor other process or ports.

It automatically handles system messages for the programmer.

This can be thought of being similar to a gen_server.

## Supervisor

A process that handles the starting and restarting of other processes.

The programmer cannot add additional functionality to the supervisor process.

## Agent

A specialised actor process that holds some state and receives messages containing functions that transform the held state.

The programmer cannot define a custom accepted message type for these.

It cannot monitor other process or ports, and cannot trap exits.

It automatically handles system messages for the programmer.

## Task

A process that performs an item of work asynchronously, sending back the response.

The programmer cannot add additional functionality to the supervisor process.

## One shot

A process that performs an item of work asynchronously, discarding any response.

**Comment by timbuchwaldt** [comment]
Coming from an Elixir-background those names sound really reasonable!
