### ISSUE TITLE
Max restart intensity defaults are reversed from Erlang

### ISSUE THREAD

**Issue by digitalcora** [gleam-lang/otp#45]
When starting a supervisor using `supervisor.start`, the max restart intensity defaults to [5 restarts per 1 second](https://github.com/gleam-lang/otp/blob/v0.5.3/src/gleam/otp/supervisor.gleam#L358-L359). This is the reverse of the default values in Erlang, which allow [1 restart per 5 seconds](https://www.erlang.org/doc/design_principles/sup_princ.html#maximum-restart-intensity). Since the defaults when using `start` are not documented, I wasn't sure whether this was an intentional divergence from Erlang's defaults or just an oversight. I would be happy to PR a doc update and/or a fix, depending on which of those it is.

**Comment by lpil** [comment]
Oops, yes, that's an accident 😁
