### ISSUE TITLE
[Discussion] Allow `actor` to change its selector after creation

### ISSUE THREAD

**Issue by rawhat** [gleam-lang/otp#47]
This came up during the process of supporting user-defined messages in `mist` WebSockets.

The way I am looking at structuring it currently does not allow for a user to pass a selector. This is because the actor `init` is called when the socket opens. This will be well before any user handler hits the path to upgrade the connection.

We talked about this on Discord, and I think landed on "lets talk about it" before actually moving forward with anything.

Right now the `Subject` passed around from the actor is all related to the consumer's messages. I'm not sure what exactly a good API would look like to update the selector. Maybe an additional type for `actor.Next`?

**Comment by lpil** [comment]
I think this would be useful, for sure.

Adding a new variant or such to `Next` sounds good. I think we'd want it to replace the selector rather than add to it so that the programmer can remove from the selector.

I can't think of any drawbacks, can you?

**Comment by rawhat** [comment]
I'm curious, if we replaced, would you still be able to reference a selector created on `init`?  Just wondering if replacing would break the ability to use your `new_subject` but extend it.


Otherwise, I think this makes a lot of sense!

**Comment by arnarg** [comment]
> I'm curious, if we replaced, would you still be able to reference a selector created on `init`? Just wondering if replacing would break the ability to use your `new_subject` but extend it.
> 
> Otherwise, I think this makes a lot of sense!

If you only want to add to it you can use [merge_selector](https://hexdocs.pm/gleam_erlang/gleam/erlang/process.html#merge_selector) otherwise you could store your "base" selector in the state and rebuild the extra ones at any point, right?

**Comment by lpil** [comment]
I think that would be the way to go!

**Comment by arnarg** [comment]
I had some free time on my hands and I implemented a sample implementation of this.

https://github.com/arnarg/otp/commit/f03a6c364c0fb2240b44fb294e5323ec68d2b638

@lpil would this be satisfactory and is the test good enough? I wasn't sure how I would create a correctly typed subject after the selector was changed without a lot of extra logic in the actor.

**Comment by lpil** [comment]
Seems like we're all in agreement, let's continue to a PR!
