### ISSUE TITLE
[Bug] Cannot not be compile after add `gleam_otp`

### ISSUE THREAD

**Issue by septemhill** [gleam-lang/otp#49]
After I run `gleam add gleam_top` under my terminal, the `gleam.tomk` add one more dependency 
for `gleam_top` (gleam_otp = "~> 0.7")

But when I ran `gleam run`, it just show me the following error: 

![Screenshot 2023-09-01 at 6 58 49 PM](https://github.com/gleam-lang/otp/assets/1216949/01bbe59e-db78-4f54-9eba-ccce80ce96db)

The gleam version is `0.30.5`, and I ran it under MacOS, installed by homebrew

**Comment by lpil** [comment]
Hello! You need to upgrade your `gleam_erlang` version. Perhaps run `gleam update`.
