### ISSUE TITLE
Current main breaks builds of gleam-elli

### ISSUE THREAD

**Issue by timbuchwaldt** [gleam-lang/otp#6]
Sadly the currently pushed commit on the main branch breaks  `gleam-experiments/elli` - This can be fixed by pinning this repo to an older commit without this issue but still might repel some people :)

**Comment by lpil** [comment]
That's right, sorry about that. I'm currently making some big changes in this library, once they are more-or-less done I'll update the other libraries to match.

**Comment by timbuchwaldt** [comment]
Haha no worries, just wanted to let you know people stumble about this :) Thanks for this great project, you're literally working on a language I always wanted since learning about Erlang :)

**Comment by lpil** [comment]
Thank you! It's the language I want too :) 

Thanks for trying it out, let me know if I can help with anything or if you would like to get involved at all.

**Comment by lpil** [comment]
I've fixed up the Elli repo, sorry for that!

**Comment by timbuchwaldt** [comment]
Awesome! Thanks for the quick fix and no worries :) I guess you'll hear from me in other repos :P
