### ISSUE TITLE
Current status of gleam/otp/actor

### ISSUE THREAD

**Issue by timbuchwaldt** [gleam-lang/otp#7]
Playing more with Gleam I had to play with actors and how they will become typed, my biggest gripe with dialyzer and Erlang/Elixir. I assume the typing is tied to the `Channel` that's used to pass messages around, right?
If so: I read through the actor source and didn't find a way to get a channel to the actor after starting it with a spec as is done in the tests. Is this just rough state because of active development or did I miss a piece?

Also regarding this concept I was wondering how typing would fit into things like dynamic process registries.

**Comment by lpil** [comment]
Hi @timbuchwaldt ! I'm still in the process of upgrading actor after the move to channels, so it's not quite usable yet. The main problem (as you've worked out) is that [the actor's channel](https://github.com/gleam-lang/otp/blob/0daf6e270461184ee5ab7381c4a5ddc053320d01/src/gleam/otp/actor.gleam#L140) is created but never shared, so it's not possible to send any messages to it.

I'm working on the compiler at the moment but I'll fix this soon (or you could have a go? 😁 )

The main thing I'm wondering is what should the `start` function return. Perhaps `Result(tuple(Pid, state), FailureReason)`. This would break compatibility with Erlang's supervisors but we could include a function that converts it to `{ok, Pid, State} | {error, Reason}` which they do accept.

**Comment by timbuchwaldt** [comment]
I can sure give it a try, yes! :)
