### ISSUE TITLE
Actor's `init` taking longer than `init_timeout` causes entire program to crash

### ISSUE THREAD

**Issue by brettkolodny** [gleam-lang/otp#73]
Like the title describes, I've run into an issue where if the `init`takes too long instead of returning an error then `actor.start_spec` will crash the entire program with the following error:

```
Runtime terminating during boot (killed)

Crash dump is being written to: erl_crash.dump...done
```

I'm using `Erlang/OTP 27` and have tried on `Erlang/OTP 25` with the same result.

Below is a code snippet that demonstrates the issue.

```gleam
import gleam/erlang/process
import gleam/option
import gleam/otp/actor

pub type State {
  State(Int)
}

pub type Message {
  Increment
}

pub fn main() {
  start_actor()

  process.sleep_forever()
}

pub fn start_actor() {
  let spec: actor.Spec(State, Message) =
    actor.Spec(init:, init_timeout: 10, loop:)

  actor.start_spec(spec)
}

pub fn init() {
  process.sleep(1_000_000)
  actor.Ready(State(0), process.new_selector())
}

pub fn loop(_message, state) {
  actor.Continue(state, option.None)
}
```

**Comment by lpil** [comment]
Hello! the program is crashing as the linked child process is timing out and it is not supervised, so the exit continues to propagates until it reaches a process trapping exits (there is not one in this case) or until it reaches the root process, crashing the program.

Do you have some particular issue?

**Comment by brettkolodny** [comment]
If this is the expected behavior maybe I'm misunderstanding the documentation, or something specific about my implementation then. It says [here](https://hexdocs.pm/gleam_otp/gleam/otp/actor.html#start_spec):

> Start an actor from a given specification. If the actor’s init function returns an error or does not return within init_timeout then an error is returned.

Based on the documentation my assumption was that the code above wouldn't crash but instead would instead return `Error(StatError)`. Maybe the language "returns an error" is a bit overloaded here and it would be clearer to re-word it?

**Comment by CrowdHailer** [comment]
My opinion has not changed. But I don't have any new compelling arguments.

**Comment by lpil** [comment]
What were your old arguments? If you can remember the details 😄

**Comment by CrowdHailer** [comment]
I think that you should always be able to validate the initial state before calling an init. And you shouldn't rely on anther pid/service without you actor understanding failure in reaching that service. I think Async init was a problem. I dunno, I'd have to play again to make better arguments
